packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  typescript:  "5.9.2"
  dotenv-cli: "^10.0.0"
  zod: "^4.0.15"
  "@types/node": "^24.2.1"
  "@t3-oss/env-core": "^0.13.8"
  "@tanstack/react-form": "^1.19.1"

catalogs:
  prisma:
    "@prisma/client": "6.13.0"
    prisma: "6.13.0"
  react19:
    react: "19.1.0"
    react-dom: "19.1.0"
    "@types/react": "19.1.0"
    "@types/react-dom": "19.1.1"